apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{  .Chart.Name }}-application-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
    {{ if and (eq .Values.service.type "NodePort") }}
    nodePort: {{ .Values.service.nodePort }}
    {{ end }}
  selector:
    app: "{{  .Chart.Name }}"
